### ISSUE TITLE
failed to read pup_update0

### ISSUE THREAD

**Issue by smran** [idc/ps4-pup_decrypt#2]
Connected
Failed to open /dev/pup_update0!
Bye!

why is that happens ?

**Comment by idc** [comment]
pup_decrypt needs sufficient permissions to access /dev/pup_update0-- you need to have broken the sandbox in-process. If the browser gets closed and restarted, you have to break the sandbox again.

Typically I run the dlclose payload, then run pup_decrypt payload after without closing the browser.

**Comment by smran** [comment]
Thanks,that works like charm!
